# Generated by Django 3.0.6 on 2020-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Play'), ('N', 'Normal')], default='SELECT CATEGORY', max_length=20)),
                ('created_at', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
